language: node_js
node_js:
  - node
  - lts/*
before_install:
  - export PATH=$PATH:`yarn global bin`
  - yarn global add greenkeeper-lockfile@1
install: yarn
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  - provider: npm
    skip_cleanup: true
    email: mats.pfeiffer@googlemail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always